name: Zapan
version: ${project.version}
main: jayson.json.zapan.Zapan
api-version: 1.16
commands:
  sethealth:
    description: Ändert das Leben eines Spielers (2 - 2048)
    usage: /<command> <spieler> <leben>
  area:
    description: Erstellt ein Gebiet
    usage: /<command> <name> <area>
  guild:
    description: Guild Commands
    usage: /<command>
  giveItem:
    description: Gibt ein eigenes Item
    usage: /<command> <itemID>
  items:
    description: Zeit alle Items an
    usage: /<command>
permissions:
  zapan.sethealth:
    description: SetHealth
    default: false