name: Zapan
version: ${project.version}
main: jayson.json.zapan.Zapan
api-version: 1.16
commands:
  sethealth:
    description: Ändert das Leben eines Spielers (2 - 2048)
    usage: /<command> <spieler> <leben>
  area:
    description: Erstellt ein Gebiet
    usage: /<command> <name> <area>
  guild:
    description: Guild Commands
    usage: /<command>
  giveItem:
    description: Gibt ein eigenes Item
    usage: /<command> <itemID>
  items:
    description: Zeit alle Items an
    usage: /<command>
  npc:
    description: NPC
    usage: /<command>
  gba:
    description: NPC
    usage: /<command>
  gmc:
    description: gamemode creative
    usage: /gmc
  gms:
    description: gamemode survival
    usage: /gms
  gma:
    description: gamemode adventure,
    usage: /gma
  gmsp:
    description: gamemode spectator
    usage: /gmsp
  discordlink:
    description: sends discord code
    usage: /discordlink
permissions:
  zapan.sethealth:
    description: SetHealth
    default: false